name: 'Create Planetscale Dev Branch'
author: 'Adam Barito'
description: 'Create Planetscale Dev Branch'

inputs:
  action:
    description: "accepts 'create', 'deploy', or 'delete'"
    type: string
    required: true

  parent-branch:
    description: 'The parent branch to create a new dev branch from, or merge current dev branch into. Defaults to main.'
    required: false
    type: string    

  branch-name:
    description: 'The name of the dev branch. Defaults to name of current git branch.'
    required: false
    type: string    

runs:
  using: 'node16'
  main: 'dist/index.js'
