name: 'Create Planetscale Dev Branch'
author: 'Adam Barito'
description: 'Create Planetscale Dev Branch'

inputs:
  action:
    description: "accepts 'create', 'deploy', or 'delete'"
    type: string
    required: true

  parent-branch:
    description: 'The parent branch to create a new dev branch from, or merge current dev branch into.'
    required: false
    type: string
    default: main

  branch-name:
    description: 'The name of the dev branch'
    required: false
    type: string
    # default to current branch name
    default: ${{ github.ref.replace('refs/heads/', '') }}

runs:
  using: 'node16'
  main: 'dist/index.js'
