name: 'Planetscale Action'

author: 'barelylabs'

description: 'Create, deploy, or delete a Planetscale branch.'

inputs:
  action:
    description: "accepts 'create-branch', 'open-deploy-request', 'queue-deploy-request', or 'delete-branch'"
    type: string
    required: true

  parent-branch-name:
    description: 'The parent branch to create a new dev branch from, or merge current dev branch into. Defaults to main.'
    required: false
    type: string

  branch-name:
    description: 'The name of the dev branch. Defaults to name of current git branch.'
    required: false
    type: string

  overwrite-branch:
    description: 'Whether to overwrite an existing dev branch. Defaults to false.'
    required: false
    type: boolean
    default: false

runs:
  using: 'node16'
  main: 'dist/index.js'
# outputs:
#   branch-name
#   branch-status
#   connection-string
#   deploy-request-number
#   deploy-request-state
#   deploy-request-deployment-state

